// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartStore.CouponsAPI.Data;

#nullable disable

namespace SmartStore.CouponsAPI.Data.Migrations
{
    [DbContext(typeof(CouponDbContext))]
    [Migration("20230402214049_UpdateCouponsTable")]
    partial class UpdateCouponsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SmartStore.CouponsAPI.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"), 1L, 1);

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("DiscountAmount")
                        .HasColumnType("real");

                    b.Property<int>("NumberOfCoupon")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfUsedCoupon")
                        .HasColumnType("int");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            CouponCode = "10OFF",
                            DiscountAmount = 0.1f,
                            NumberOfCoupon = 50,
                            NumberOfUsedCoupon = 0
                        },
                        new
                        {
                            CouponId = 2,
                            CouponCode = "20OFF",
                            DiscountAmount = 0.2f,
                            NumberOfCoupon = 30,
                            NumberOfUsedCoupon = 0
                        },
                        new
                        {
                            CouponId = 3,
                            CouponCode = "50OFF",
                            DiscountAmount = 0.5f,
                            NumberOfCoupon = 10,
                            NumberOfUsedCoupon = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
