// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartStore.ProductsAPI.Data;

#nullable disable

namespace SmartStore.ProductsAPI.Data.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    partial class ProductsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SmartStore.ProductsAPI.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Laptops",
                            Description = "MSI GF63 Thin Gaming Laptop - Intel Core I5 - 8GB RAM - 256GB SSD - 15.6-inch FHD - 4GB GPU - Windows 10 - Black (English Keyboard).",
                            Name = "MSI GF63 Thin Gaming Laptop",
                            PictureUrl = "/images/products/1.jpg",
                            Price = 4600m,
                            Quantity = 20m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Laptops",
                            Description = "DELL G3 15-3500 Gaming Laptop - Intel Core I5-10300H - 8GB RAM - 256GB SSD + 1TB HDD - 15.6-inch FHD - 4GB GTX 1650 GPU - Ubuntu - Black.",
                            Name = "DELL G3 15-3500 Gaming Laptop",
                            PictureUrl = "/images/products/2.jpg",
                            Price = 3500m,
                            Quantity = 25m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Televisions",
                            Description = "Samsung UA43T5300 - 43-inch Full HD Smart TV With Built-In Receiver.",
                            Name = "Samsung UA43T5300",
                            PictureUrl = "/images/products/3.jpg",
                            Price = 1600m,
                            Quantity = 50m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Televisions",
                            Description = "LG 43LM6370PVA - 43-inch Full HD Smart TV With Built-in Receiver.",
                            Name = "LG 43LM6370PVA",
                            PictureUrl = "/images/products/4.jpg",
                            Price = 660m,
                            Quantity = 35m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Mobile Phones",
                            Description = "Samsung Galaxy A12 - 6.4-inch 128GB/4GB Dual SIM Mobile Phone - White.",
                            Name = "Samsung Galaxy A12",
                            PictureUrl = "/images/products/5.jpg",
                            Price = 950m,
                            Quantity = 70m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Mobile Phones",
                            Description = "Apple iPhone 12 Pro Max Dual SIM with FaceTime - 256GB - Pacific Blue.",
                            Name = "Apple iPhone 12 Pro Max",
                            PictureUrl = "/images/products/6.jpg",
                            Price = 4300m,
                            Quantity = 65m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Mobile Accessories",
                            Description = "OPPO Realme 8 Pro Case, Dual Layer PC Back TPU Bumper Hybrid No-Slip Shockproof Cover For OPPO Realme 8 / Realme 8 Pro 4G.",
                            Name = "OPPO Realme 8 Pro Case",
                            PictureUrl = "/images/products/7.jpg",
                            Price = 1500m,
                            Quantity = 40m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Mobile Accessories",
                            Description = "Galaxy Z Flip3 5G Case, Slim Luxury Electroplate Frame Crystal Clear Back Protective Case Cover For Samsung Galaxy Z Flip 3 5G Purple.",
                            Name = "Galaxy Z Flip3 5G Case",
                            PictureUrl = "/images/products/8.jpg",
                            Price = 4000m,
                            Quantity = 40m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
